### ISSUE TITLE
[Bug] mj生成的图片链接访问不了

### ISSUE THREAD

**Issue by harochen75** [Zo3i/chatgptWithMidjourney#12]
图片链接可以自行进行反向代理。找一台国内能访问的境外服务器或者香港台湾的，配置一个nginx 即可解决。

尝试配置了
    location / {
        proxy_pass https://cdn.discordapp.com;
        proxy_set_header Host cdn.discordapp.com;
        proxy_set_header X-Real-IP $remote_addr;
    }
    
  还是访问不了。 是哪里配置错了嘛？

**Comment by Zo3i** [comment]
https://media.discordapp.net/attachments/1093565789782675476/1107884228399607878/landing_airplane_0423a88b-7343-40b7-81bf-772c42b54df5.png?width=968&height=968


https://img.zxx.im/attachments/1093565789782675476/1107884228399607878/landing_airplane_0423a88b-7343-40b7-81bf-772c42b54df5.png?width=968&height=968


这是反向代理之后的地址。




server {
        listen 80;
        server_name img.zxx.im;

        #开启和关闭gzip模式
        gzip on;
        #gizp压缩起点，文件大于1k才进行压缩
        gzip_min_length 1k;
        # gzip 压缩级别，1-9，数字越大压缩的越好，也越占用CPU时间
        gzip_comp_level 1;
        # 进行压缩的文件类型。
        gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript ;
        #nginx对于静态文件的处理模块，开启后会寻找以.gz结尾的文件，直接返回，不会占用cpu进行压缩，如果找不到则不进行压缩
        gzip_static on;
        # 是否在http header中添加Vary: Accept-Encoding，建议开启
        gzip_vary on;
        # 设置压缩所需要的缓冲区大小，以4k为单位，如果文件为7k则申请2*4k的缓冲区
        gzip_buffers 2 4k;
        # 设置gzip压缩针对的HTTP协议版本
        gzip_http_version 1.1;

        charset utf-8;
        error_page   500 502 503 504  /50x.html;

        location / {
            proxy_pass https://cdn.discordapp.com/;
        }
    }


这是nginx配置，你照这个设置就行

**Comment by harochen75** [comment]
还是不行。 可能是因为我的是http的地址。  反向代理的是https。 试了增加proxy_redirect https:// http://;    还是访问不了

**Comment by Zo3i** [comment]
建议使用https

**Comment by pengboooo** [comment]
你是如何解决的呀？我页遇到这样的问题了

**Comment by Zo3i** [comment]
已经写的很清楚了。你遇到什么问题要具体说清楚。报错截图出来
