### ISSUE TITLE
操作失败

### ISSUE THREAD

**Issue by x0620x** [Zo3i/chatgptWithMidjourney#15]
我在 配置里加了 midjourneyapi 然后发送/mj 图片绘画，提示：操作失败，Required request body is missing: public org.jeecg.common.api.vo.Result<?> org.jeecg.modules.midjourney.controller.WebhookController.request(org.jeecg.modules.midjourney.data.Msg,javax.servlet.http.HttpServletRequest)

**Comment by Zo3i** [comment]
可能是你的配置错了。默认是不用配置midjourneyapi的。

**Comment by x0620x** [comment]
> 可能是你的配置错了。默认是不用配置midjourneyapi的。

设置的页面不需要填入 midjourneyapi 吗？

**Comment by Zo3i** [comment]
可以不写

**Comment by x0620x** [comment]
> 可以不写

我看您写的示例 .env.local 需要创建，然后添加参数
意思是在项目跟目录创建这个文件，然后加入示例的那四个参数吗？
还是说，这个不需要，直接部署运行后在设置里输入opai的key 和 mj的key 就可以了
我想的场景是，项目里配置opai的key和mj的key，用户只需要输入密码就可以使用了。如本项目原版那样，在部署的时候通过环境变量就可以设置默认的opaikey。

**Comment by Zo3i** [comment]
项目里配置opai的key和mj的key 你理解的是对的。其他不用配置就能跑。

**Comment by x0620x** [comment]
非肥肠感谢您的回答，还有一个疑问，是否只需要在项目跟目录下创建 env.local 文件，并只配置 MIDJOURNEY_API_KEY= 一个参数即可。

**Comment by Zo3i** [comment]
只是做图是够了。

**Comment by x0620x** [comment]
> 只是做图是够了。

您好，我在本地开发进行测试，根目录下创建 env.local 文件，并只配置 MIDJOURNEY_API_KEY= 这一个参数，然后在使用的时候总会报错（操作失败，Required request body is missing: public org.jeecg.common.api.vo.Result<?> org.jeecg.modules.midjourney.controller.WebhookController.request(org.jeecg.modules.midjourney.data.Msg,javax.servlet.http.HttpServletRequest)） 并不知道是不是网络的问题，现在我准备放弃本地开发，如果在 vercel 上部署，不想让用户输入，可否使用 Environment Variables 环境变量来指定 MIDJOURNEY 的key呢？

**Comment by Zo3i** [comment]
嗯可以的
