### ISSUE TITLE
[Bug] https://midjourneyapi.zxx.im/main 付款后报错

### ISSUE THREAD

**Issue by michael7908** [Zo3i/chatgptWithMidjourney#17]
ask is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...
task is create please wait...

please fix this,thanks

**Comment by Zo3i** [comment]
the problem was solved
