### ISSUE TITLE
[Feature] 提pr到主项目

### ISSUE THREAD

**Issue by zyqq** [Zo3i/chatgptWithMidjourney#19]
**这个功能与现有的问题有关吗？**
如果有关，请在此列出链接或者描述问题。

**你想要什么功能或者有什么建议？**
为什么不提pr到https://github.com/Yidadaa/ChatGPT-Next-Web呢

**有没有可以参考的同类竞品？**
可以给出参考产品的链接或者截图。

**其他信息**
可以说说你的其他考虑。

**Comment by Zo3i** [comment]
1、因为边学边写。写的比较烂。2、改动有点大，把一些重要的部分改了。
