### ISSUE TITLE
[Bug] 不挂代理mj图片不显示

### ISSUE THREAD

**Issue by lin-1259** [Zo3i/chatgptWithMidjourney#21]
如何更改MJ的反向代理

**Comment by Zo3i** [comment]
看看文档。这个参数MIDJOURNEY_IMG_PROXY

**Comment by qq2848045** [comment]
> 看看文档。这个参数MIDJOURNEY_IMG_PROXY

嗯嗯  我看到了大佬- - 但是我不会用，是在docker的时候把这个变量填进去嘛，应该填什么，怎么反向代理，谢谢大佬解答

**Comment by Zo3i** [comment]
不会用建议百度，谷歌。提问具体的问题，我不负责教你怎么使用。

**Comment by qq2848045** [comment]
好滴，谢谢大佬
