### ISSUE TITLE
[Bug] AI绘画出问题了

### ISSUE THREAD

**Issue by lin-1259** [Zo3i/chatgptWithMidjourney#23]
![Snipaste_2023-06-16_03-56-11](https://github.com/Zo3i/chatgptWithMidjourney/assets/60593825/6fb53f2e-21e8-4949-b146-c31701e0e19e)

AI绘画提示：{"code": 50035, "errors": {"data": {"_errors": [{"code": "INTERACTION_APPLICATION_COMMAND_INVALID_VERSION", "message": "\u8be5\u6743\u9650\u5df2\u8fc7\u65f6\uff0c\u8bf7\u7a0d\u5019\u51e0\u5206\u949f\u518d\u8bd5"}]}}, "message": "Invalid Form Body"}

刚才重新docker了一下就这样了，我以为是我操作有问题，然后我又在vercel试了试发现还是如此，应该不是我的操作问题吧

**Comment by Zo3i** [comment]
MJ官方升级，现在已经修复了。
