### ISSUE TITLE
[Bug] docker还没更新吗

### ISSUE THREAD

**Issue by lin-1259** [Zo3i/chatgptWithMidjourney#24]
大佬你好，dooker还没更新吗，部署在vercel上经常漏字，用户体验忒不好了

**Comment by lin-1259** [comment]
大佬后期还会更新嘛,目前我有500多个客户都在用着我用您这个源码打出来的站点,很多人可能都充值了积分,希望能一直保持更新,最好把绘图加上识图和混图功能,就像这个项目一样:https://github.com/Licoy/ChatGPT-Midjourney

**Comment by Zo3i** [comment]
最近老是忘记，代码已经更新了。但是docker 没同步。其他功能等我有空加一下。

**Comment by lin-1259** [comment]
> 最近老是忘记，代码已经更新了。但是docker 没同步。其他功能等我有空加一下。

好滴谢谢大佬,期待更新

**Comment by Zo3i** [comment]
已经更新了

**Comment by lin-1259** [comment]
嗯哈  docker的时候报错了
`WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v1) and no specific platform was `requested``
我查了查,貌似是平台不匹配,说是添加一个这个代码:--platform linux/amd64,但是添加了也不管用,求大佬指点一下

**Comment by lin-1259** [comment]
> 已经更新了

嗯哈 docker的时候报错了
`WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v1) and no specific platform was requested`
我查了查,貌似是平台不匹配,说是添加一个这个代码:--platform linux/amd64,但是添加了也不管用,求大佬指点一下

**Comment by lin-1259** [comment]
> 已经更新了

我这样写之后不报错了,但是镜像并没有启动:

```
docker pull zo3i/chatgptwithmidjourney

docker run -d -p 3000:3000 \
   --platform linux/arm64 \
   -e OPENAI_API_KEY="" \
   -e CODE="" \
   zo3i/chatgptwithmidjourney
```

**Comment by Zo3i** [comment]
已经修复了

**Comment by lin-1259** [comment]
> 已经修复了

谢谢大佬，已经更新了，没有问题，期待后续更新

**Comment by lin-1259** [comment]
> 已经修复了

大佬  我这有个客户说付完款但是积分没有增加 ,您给看看

他的账户是 20910676@qq.com 

他在今天 15:07:46 充了1美刀

但是充值完成后

回首页一看积分还是0

![mmexport1689236770096](https://github.com/Zo3i/chatgptWithMidjourney/assets/60593825/5d454050-2d5a-45d4-8133-f59b5f576bab)
![mmexport1689236765313](https://github.com/Zo3i/chatgptWithMidjourney/assets/60593825/83a1f36a-f5fc-4e7b-9b6d-eeac32f76ed9)

大佬可以加个联系方式吗

我的V : WTFFJL

谢谢大佬
