### ISSUE TITLE
[Bug] 图片显示不出来

### ISSUE THREAD

**Issue by leochen12-rgb** [Zo3i/chatgptWithMidjourney#3]
破图了，文字显示出来了，U1 V1 reset都显示出来，唯独图片无法显示，请教是什么原因导致的
新加坡节点服务器

**Comment by Zo3i** [comment]
可以看看控制台network里面的图片能不能单独打开。

**Comment by leochen12-rgb** [comment]
> 可以看看控制台network里面的图片能不能单独打开。

原来是cdn地址国内打不开。。
