### ISSUE TITLE
为什么创建了 输入了秘钥 加载不出来图片呢 

### ISSUE THREAD

**Issue by 205637827** [Zo3i/chatgptWithMidjourney#4]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by Zo3i** [comment]
<img width="826" alt="image" src="https://github.com/Zo3i/chatgptWithMidjourney/assets/30296801/43d04b02-2bef-4335-9262-5489ca7b02e6">
需要定义mj api url 如上图。

**Comment by 205637827** [comment]
好的 感谢指导

**Comment by 205637827** [comment]
命令可以收到了 但是图片加载不出来呢

**Comment by Zo3i** [comment]
请截图说明。不然没法具体定位问题呢（敏感信息注意打码

**Comment by 205637827** [comment]
![1684295886763](https://github.com/Zo3i/chatgptWithMidjourney/assets/98471590/cd3561dc-57df-4ccc-b945-a546843d08f5)
图片加载不出来

**Comment by Zo3i** [comment]
这是因为你的网络环境问题吧。国内访问需要反向代理，或是科学上网。

**Comment by 205637827** [comment]
这是添加域名之后的呢

**Comment by Zo3i** [comment]
打开控制台。查看图片地址，检查能否当读打开。

**Comment by 205637827** [comment]
估计就是需要梯子 我用手机加上魔法后 可以加载出来
