### ISSUE TITLE
[Bug] 输入/mj指令不返回内容

### ISSUE THREAD

**Issue by 504001687** [Zo3i/chatgptWithMidjourney#5]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [x] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [x] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [x] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
/mj 加描述不返回内容

**如何复现**
正常操作 /mj + 指令
**截图**

![WX20230517-160807@2x](https://github.com/Zo3i/chatgptWithMidjourney/assets/38887956/12bcc9ca-f39a-4ba7-af1e-aeebd23806f3)
环境变量页设置了

![WX20230517-161111@2x](https://github.com/Zo3i/chatgptWithMidjourney/assets/38887956/4e55a3ad-775c-4fed-ad56-7cc8346bea97)

**一些必要的信息**
 - 系统：[macos 12]
 - 浏览器： [safari]
 - 版本： [20230516]
 - 部署方式：[vercel]

**Comment by Zo3i** [comment]
环境变量设置之后重新部署了吗。打开浏览器控制台截个图看看请求情况。

**Comment by 504001687** [comment]
![321](https://github.com/Zo3i/chatgptWithMidjourney/assets/38887956/7b26521e-7313-4a13-8ef4-17d9e5b0c95b)
感谢您的耐心解答，但是我重新输入prompt ，还是提示有引号

**Comment by Zo3i** [comment]
看看你请求发送了什么。request里面发送的prompt。我在后台没找到你发送的prompt

**Comment by 504001687** [comment]
![payload](https://github.com/Zo3i/chatgptWithMidjourney/assets/38887956/15d28ea3-727f-4e2e-a1e2-ecf6b38dca54)

![response](https://github.com/Zo3i/chatgptWithMidjourney/assets/38887956/fcb36730-bb38-4639-905c-91e2a7e417c7)

**Comment by 504001687** [comment]
请求参数：
action: "CREATE_IMAGE", fast: false, prompt: " A boy look cute"}
action: "CREATE_IMAGE"
fast: false
prompt: " A boy look cute"
请求返回值：
```json
{}
```

**Comment by 504001687** [comment]
请求参数：
action: "CREATE_IMAGE", fast: false, prompt: " A boy look cute"}
action: "CREATE_IMAGE"
fast: false
prompt: " A boy look cute"
请求返回值：
```json
{}
```

**Comment by Zo3i** [comment]
你这个返回不对劲。api 文档里有写。你可以对着参考一下。
<img width="1243" alt="image" src="https://github.com/Zo3i/chatgptWithMidjourney/assets/30296801/84f16338-a3c5-4702-b78f-cdd247bd65c2">

**Comment by 504001687** [comment]
我测试了官方的api 用自己的key 正常返回了，但是您这个next的就返回‘’‘josn{}'''

**Comment by Zo3i** [comment]
建议拉取一下最新代码，重新部署一下。最新代码配置一下api url 的环境变量就行了。
