### ISSUE TITLE
你好，这个支持图生图，垫图这个功能吗？api 是快速出图的吗？

### ISSUE THREAD

**Issue by itxtl** [Zo3i/chatgptWithMidjourney#6]
你好，这个支持图生图，垫图这个功能吗？api 是快速出图的吗？

**Comment by Zo3i** [comment]
你好👋，图生图功能正在开发中。API 可选快慢出图。

**Comment by fange111** [comment]
你好，https://midjourneyapi.zxx.im/main这个API 是买了线路 还要买积分 才可以使用  还是单买一个，线路是包月，积分是按量算？官网没写，有点傻傻分不清

**Comment by Zo3i** [comment]
@fange111 你好👋 有问题单独开一个issues哈。线路和积分是这样的，普通用户默认只能同时运行一个制图任务。如果需要同时制作多张图片就需要购买包月线程。制图是需要积分的，慢速制图1积分。快速制图5积分。
