### ISSUE TITLE
[Bug] 你好，也就是说购买了快速线路，就可以使用积分 同时做多个图了，是这个意思吗？

### ISSUE THREAD

**Issue by fange111** [Zo3i/chatgptWithMidjourney#7]
**反馈须知**

⚠️ 注意：不遵循此模板的任何帖子都会被立即关闭。

请在下方中括号内输入 x 来表示你已经知晓相关内容。
- [ ] 我确认已经在 [常见问题](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/faq-cn.md) 中搜索了此次反馈的问题，没有找到解答；
- [ ] 我确认已经在 [Issues](https://github.com/Yidadaa/ChatGPT-Next-Web/issues) 列表（包括已经 Close 的）中搜索了此次反馈的问题，没有找到解答。
- [ ] 我确认已经在 [Vercel 使用教程](https://github.com/Yidadaa/ChatGPT-Next-Web/blob/main/docs/vercel-cn.md) 中搜索了此次反馈的问题，没有找到解答。

**描述问题**
请在此描述你遇到了什么问题。

**如何复现**
请告诉我们你是通过什么操作触发的该问题。

**截图**
请在此提供控制台截图、屏幕截图或者服务端的 log 截图。

**一些必要的信息**
 - 系统：[比如 windows 10/ macos 12/ linux / android 11 / ios 16]
 - 浏览器： [比如 chrome, safari]
 - 版本： [填写设置页面的版本号]
 - 部署方式：[比如 vercel、docker 或者服务器部署]

**Comment by fange111** [comment]
你好，也就是说购买了快速线路，就可以使用积分 同时做多个图了，是这个意思吗？  另外，刚才测试，返回的图片链接需要有梯子才可以显示，没有梯子 是无法显示的

**Comment by Zo3i** [comment]
对的。买线程是可以同时做多个图。制图都是需要积分的。图片链接可以自行进行反向代理。找一台国内能访问的境外服务器或者香港台湾的，配置一个nginx 即可解决。

**Comment by harochen75** [comment]
要怎么配置呢?

**Comment by Zo3i** [comment]
@harochen75 要问问提重新开一个issues。还有描述清楚问题。

**Comment by harochen75** [comment]
> 对的。买线程是可以同时做多个图。制图都是需要积分的。图片链接可以自行进行反向代理。找一台国内能访问的境外服务器或者香港台湾的，配置一个nginx 即可解决。

对应的nginx怎么配置呢？
