### ISSUE TITLE
[Bug] 作图失败时CREDIT点数不退还

### ISSUE THREAD

**Issue by Qianxia666** [Zo3i/chatgptWithMidjourney#9]
已付费支持，但是还有一点疑问：出现以下提示后CREDIT点数不退还，想问一下是BUG还是运行机制相关原因？

task is create please wait...
your task is being processed...
your task is timeout...

**Comment by Zo3i** [comment]
感谢支持🙏，出现任务超时一般是因为敏感内容，或是输入参数有误。在下一个版本会修复
